### ISSUE TITLE
Variant_Classification problems

### ISSUE THREAD

**Issue by shirleydaidai** [griffithlab/GenVisR#272]
I noticed the appropriate Variant_Classification in the MAF files including: Nonsense_Mutation  Frame_Shift_Ins Frame_Shift_Del Translation_Start_Site  Splice_Site Nonstop_Mutation    In_Frame_Ins    In_Frame_Del    Missense_Mutation   5'Flank 3'Flank 5'UTR   3'UTR   RNA Intron  IGR Silent  Targeted_Region.

But I have the following types which were not in the above list: Start_Codon_SNP, Start_Codon_Del, Stop_Codon_Del, Stop_Codon_Ins, De_novo_Start_OutOfFrame, De_novo_Start_InFrame...

How can I categorize these data?

**Comment by zlskidmore** [comment]
@shirleydaidai Are you referring to the waterfall function? If so there is a parameter called `variant_class_order` that takes a character vector of mutation types in order to plot the most deleterious. If you add the mutation types you specify above to that parameter there should be no problem (as long as the character vector you supply to that param has all the mutation types seen in your data set). This is briefly touched on in the waterfall vignette available here:
https://bioconductor.org/packages/3.3/bioc/vignettes/GenVisR/inst/doc/waterfall_introduction.html

However it is a little unclear, I will clear this topic up in future releases of the vignette. 

Also while not required I recommend supplying a defined color scheme via the param `mainPalette`, GenVisR::waterfall will default to a color scheme of 20 variables however colors may not match mutation (i.e. all frameshifts == red) and it will complain if you go over the 20 variables without supplying something to `mainPalette`.
