### ISSUE TITLE
cnSpec genome mapping error

### ISSUE THREAD

**Issue by CodyRamirez** [griffithlab/GenVisR#290]
This broke.

Using reference build hg38, it tries to map all the exome chromosomes and extra contigs this causes the plot to throw a fit!

Please fix this so I can conduct my science using this black box you call GenVisR

**Comment by zlskidmore** [comment]
This is occurring because it's trying to plot 250+ chromosomes/contigs on the same plot, it's doing what it's supposed to but logic needs to be put in place to limit to just chromosomes 1-22 X and Y. it does this for hg19 but for some reason seems to miss this for hg38. I suspect it's a regex problem with the way contigs are named between the two.

Shouldn't take long to fix, should also check the other references as well

**Comment by zlskidmore** [comment]
upon closer inspection it seems to be an issue with the database cytoGeno, within GenVisR which specifies the bands for each chromosome, for hg38 it has the unmapped contigs as well.

Thing to do is to put in logic to ensure that only the 23 pairs of chromosomes are pulled in by cnSpec

**Comment by CodyRamirez** [comment]
I recently found that a similar problem is occurring with lohSpec as well.
I did not want to create another issue in the hopes that your adjustment would fix both problems.
