### ISSUE TITLE
GenVisR 3.4.0

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/GenVisR#318]
Warning in install.packages :
  package ‘GenVisR’ is not available (for R version 3.4.0)

**Comment by zlskidmore** [comment]
Hey @ahwagner the GenVisR package is not on CRAN but is rather hosted on bioconductor which is why install.packages fails. to get the most up to date version you could install from github with

`devtools::install_github("griffithlab/GenVisR")`

or you could install the version from bioconductor which is update bi-anually, the instructions for that is here.

https://bioconductor.org/packages/release/bioc/html/GenVisR.html
