### ISSUE TITLE
network？

### ISSUE THREAD

**Issue by windforclouds** [griffithlab/GenVisR#372]
> lolliplot(data)
Using the following host: www.ensembl.org for biomaRt queries to change the ensembl annotation version alter this parameter!
Querying biomaRt for transcript sequence
NULL
Error in .processResults(postRes, mart = mart, sep = sep, fullXmlQuery = fullXmlQuery,  : 
  The query to the BioMart webservice returned an invalid result.
The number of columns in the result table does not equal the number of attributes in the query.
Please report this on the support site at http://support.bioconductor.org

**Comment by windforclouds** [comment]
I used the sample data

**Comment by zlskidmore** [comment]
Thanks for the report @windforclouds 

It looks like this is mostly due to changes in ensembl/biomart

https://support.bioconductor.org/p/134524/

also had to make a couple minor changes in my code

To fix you'll need to install the development version of biomaRt and the devel version of genvisr either from this repo or the bioconductor devel site.

BiocManager::install('grimbough/biomaRt')
devtools:install_github('griffithlab/GenVisR')

should work, make sure you restart R after this. I tested and it works on my end with the example data. I'll wait for your confirmation to close this issue

**Comment by windforclouds** [comment]
Thanks, my problem is solved
